using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using TravelPortal.ViewModels;

namespace TravelPortal.Views
{
    /// <summary>
    /// Логика взаимодействия для RatingControl.xaml
    /// </summary>
    public partial class AgencyRatingControl : UserControl
    {
        public AgencyRatingControl()
        {
            InitializeComponent();

            AgencyRatingViewModel model = new AgencyRatingViewModel();
            model.AutoGeneratedColumns += (sender, e) =>
            {
                Grid.Columns.Clear();
                int columnIndex = 0;
                foreach (var name in e.Headers)
                {
                    Grid.Columns.Add(
                        new DataGridTextColumn
                        {
                            Header = name,
                            Binding = new Binding(nameof(RowDataItem.Fields) +
                                                  $"[{columnIndex++}]")
                        });
                }
            };
            model.MessageBoxDisplayRequested += (sender, e) =>
            {
                CustomMessageBox.Show(e.Title, e.Text);
            };
            DataContext = model;
        }

        private void AgencyRatingControl_OnLoaded(object sender, RoutedEventArgs e)
        {
            // Устанавливаем фильтр записей (а при его изменении загружаются данные из БД)
            // после загрузки элемента управления, а не в конструкторе,
            // для того, чтобы были подключены все события ViewModel,
            // в том числе событие открытия окна сообщения (при ошибке получения записей из БД),
            // вызов которого в конструкторе вызовет ошибку,
            // и событие автогенерации столбцов,
            // вызов которого происходит после получения данных из БД.
            ((AgencyRatingViewModel)DataContext).SetDefaultFilter();
        }
    }
}
